name: "Run build"
on:
  workflow_dispatch:
    inputs:
      image_formats:
        type: string
        description: |
          Space-separated vendor formats to build.
        required: true
        default: qemu_uefi
      custom_sdk_version:
        type: string
        required: false
        description: |
          Custom SDK container version to use for this build.

  workflow_call:
    inputs:
      image_formats:
        type: string
        description: |
          Space-separated vendor formats to build.
        required: true
        default: qemu_uefi
      custom_sdk_version:
        type: string
        required: false
        description: |
          Custom SDK container version to use for this build.

permissions:
  pull-requests: write

jobs:
  packages:
    name: "Build Flatcar packages"
    runs-on:
      - ubuntu-latest
      # - debian
      # - build
      # - x64
    strategy:
      fail-fast: false
      matrix:
        arch: ["amd64", "arm64"]
    defaults:
      run:
        working-directory: scripts

    steps:
      - name: Prepare machine
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          echo "${{ inputs.custom_sdk_version }}"