name: "Test Workflow"
on:
  workflow_dispatch:
    inputs:
      lables:
        type: string
        required: false
        default: x64
      sleep:
        type: number
        required: false
        default: 20

jobs:
  doNothing1:
    name: "Do nothing1"
    runs-on:
      labels:
      - ${{ github.event.inputs.lables }}
    steps:
    - name: "Do nothing2"
      run: |
        echo "Hello world"
        sleep ${{ github.event.inputs.sleep }}
  doNothing2:
    name: "Do nothing2"
    runs-on:
      - self-hosted
      - ${{ github.event.inputs.lables }}
    steps:
    - name: "Do nothing3"
      run: |
        echo "Hello world"
        sleep ${{ github.event.inputs.sleep }}
  doNothing3:
    name: "Do nothin3"
    runs-on:
      - self-hosted
      - ${{ github.event.inputs.lables }}
    steps:
    - name: "Do nothing4"
      run: |
        echo "Hello world"
        sleep ${{ github.event.inputs.sleep }}
  doNothing4:
    name: "Do nothin4"
    runs-on:
      - self-hosted
      - ${{ github.event.inputs.lables }}
    steps:
    - name: "Do nothing5"
      run: |
        echo "Hello world"
        sleep ${{ github.event.inputs.sleep }}
