name: "Build updated SDK container"
on:
  workflow_dispatch:
    inputs:
      source_sdk_version:
        type: string
        required: false
        description: |
          Source SDK container to use. Defaults to version defined in version.txt.
      custom_sdk_version:
        type: string
        required: false
        description: |
          Custom SDK container version to build. Defaults to source SDK w/ "-github-[DATE]" appended.

  workflow_call:
    outputs:
      sdk_version:
        description: "The version of the SDK container that was built"
        value: ${{ jobs.update_sdk.outputs.sdk_version }}
    inputs:
      source_sdk_version:
        type: string
        required: false
        description: |
          Source SDK container to use. Defaults to version defined in version.txt.
      custom_sdk_version:
        type: string
        required: false
        description: |
          Custom SDK container version to build. Defaults to source SDK w/ "-github-[DATE]" appended, or
          '-github-pr-[PRNUM]-[DATE]' if the build was triggered from a PR.

permissions:
  pull-requests: write

jobs:
  update_sdk:
    name: "Build an updated SDK container image"
    runs-on:
      - ubuntu-latest
      # - self-hosted
      # - debian
      # - build
      # - x64
    strategy:
      fail-fast: false
    outputs:
      sdk_version: ${{ steps.step1.outputs.sdk_version }}
    defaults:
      run:
        working-directory: scripts

    steps:
      - name: Prepare machine
        id: step1
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          echo "sdk_version=3621.0.0+nightly-20230531-2100-github-2023_06_01__15_43_45" >> "${GITHUB_OUTPUT}"
